### ISSUE TITLE
这个管理员ID该如何填写呀，这个是不是itchat的用户是没办法使用的呀

### ISSUE THREAD

**Issue by AnCool-OvO** [Tishon1532/bridge_room#2]
求解答一下 @Tishon1532

**Comment by Tishon1532** [comment]
> 求解答一下 @Tishon1532 

只有ntchat，因为itchat没有唯一id

**Comment by AnCool-OvO** [comment]
> > 求解答一下@Tishon1532
> 
> 只有ntchat，因为itchat没有唯一id

好的感谢回复

**Comment by He0607** [comment]
> > 求解答一下@Tishon1532
> 
> 只有ntchat，因为itchat没有唯一id


对啦那如果使用的是wechaty的话是不是就是可以使用的呀
